### ISSUE TITLE
Content path does not exist

### ISSUE THREAD

**Issue by jonlovera** [beyonk-adventures/now-v2-ghost#2]
Hi there 👋, 
I was testing this repo in now v2 and for some reason I am getting the following error:

```bash
Error: Your content path does not exist! Please double check `paths.contentPath` in your custom config file e.g. config.production.json.
    at module.exports.exports.Provider.doesContentPathExist (/var/task/user/server.js:266638:15)
    at Object.loadNconf (/var/task/user/server.js:52500:11)
    at Object.<anonymous> (/var/task/user/server.js:52517:27)
    at __webpack_require__ (/var/task/user/server.js:22:30)
    at Object.module.exports.module.exports (/var/task/user/server.js:290916:16)
    at __webpack_require__ (/var/task/user/server.js:22:30)
    at Object.module.exports.Object.defineProperty.value (/var/task/user/server.js:570803:16)
    at __webpack_require__ (/var/task/user/server.js:22:30)
    at Object.<anonymous> (/var/task/user/server.js:612676:17)
    at __webpack_require__ (/var/task/user/server.js:22:30)
    at startup (/var/task/user/server.js:38:19)
    at module.exports.EMAIL_RE (/var/task/user/server.js:44:18)
    at Object.<anonymous> (/var/task/user/server.js:47:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

Here's my config.production.js
```js
"use strict";

module.exports = {
  url: "https://ghost-example.jonlov.now.sh",
  auth: {
    type: "password"
  },
  paths: {
    contentPath: undefined
  },
  logging: {
    transports: ["stdout"]
  }
};
```

The only thing that I didn't setup is my Google Storage. Is a requirement to have a storage solution? What do you think it could be? Did you run into a similar bug when deploying?

Some help will be appreciated. Thank you!

**Comment by etamity** [comment]
New ghost v2 does not support pass config as parameters anymore.
Here is one of the way to override the config.

config.js
```js
'use strict';
const { join } = require('path');
const defualtConfig = require('./node_modules/ghost/core/server/config');
const contentPath = join(__dirname, 'content');

defualtConfig.set('paths:contentPath', contentPath);
defualtConfig.set('paths:internalStoragePath', join(contentPath, 'adapters/'));
defualtConfig.set(
  'database:connection:filename',
  join(contentPath, 'data', 'ghost-dev.db')
);
module.exports = defualtConfig;
```
server.js
```js
const ghost = require('ghost');
const express = require('express');
const { join } = require('path');

// Import and override configs
require(join(__dirname, 'config.js'));


async function bootstrap() {
  const server = express();
  const ghostServer = await ghost();
  server.use('/', ghostServer.rootApp);
  ghostServer.start(server);
  return server;
}

module.exports = bootstrap();
```

**Comment by jonlovera** [comment]
@etamity did you manage to make Ghost v2 work on Zeit Now v2? I been trying and I still getting the same issue with the content path.

**Comment by etamity** [comment]
I managed to make it compiled and work locally, but not in Zeit Now V2, it always return error on server

**Comment by jonlovera** [comment]
@etamity same over here. 

I figure out that when the bundle is compiled by [ncc](https://github.com/zeit/ncc), there's some issues because of the way `Ghost` codebase works and the way [ncc](https://github.com/zeit/ncc) webpack build the file. I'm sure there's a workaround however, I haven't found out one yet.

If you want to give a try, try to bundle the `index.js` file with [ncc](https://github.com/zeit/ncc) and then try to run it with `node NAME_OF_THE_COMPILED_FILE_BY_NCC.js` and have a look at the errors. If you find out something let me know. I'll keep trying.

**Comment by etamity** [comment]
@jonlov 

Here is my config: 
```json
{
  "version": 2,
  "name": "website-musiz",
  "routes": [
    { "src": "/.*", "dest": "server.js" }
  ],
  "builds": [
    {
      "src": "content/*/*.*",
      "use": "@now/static"
    },
    {
      "src": ".env",
      "use": "@now/static"
    },
    {
      "src": "package.json",
      "use": "@now/static"
    },
    {
      "src": "MigratorConfig.js",
      "use": "@now/static"
    },
    {
      "src": "server.js",
      "use": "@now/node",
      "config": { "maxLambdaSize": "20mb" }
    }
  ],
  "alias": [
    "https://website-musiz.etamity.now.sh"
  ],
  "env": {
    "NODE_ENV": "production"
  },
  "regions": [
    "lhr"
  ]
}
```

and got these errors :

```
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/oracledb" attempted to require "oracledb" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/maria" attempted to require "mariasql" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/mssql" attempted to require "mssql" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/core/server/web/site" attempted to require "hbs" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/jsdom/lib/jsdom" attempted to require "canvas" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/bunyan/lib" attempted to require "source-map-support" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ws/lib" attempted to require "utf-8-validate" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ws/lib" attempted to require "bufferutil" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/mysql2" attempted to require "mysql2" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/oracle" attempted to require "oracle" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/postgres" attempted to require "pg-query-stream" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/postgres" attempted to require "pg" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/redshift" attempted to require "pg" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/knex/lib/dialects/strong-oracle" attempted to require "strong-oracle" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql2" attempted to require "mysql2" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/oracle" attempted to require "oracle" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/oracledb" attempted to require "oracledb" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mssql" attempted to require "mssql" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mssql" attempted to require "mssql" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mssql" attempted to require "mssql" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mssql" attempted to require "tedious" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/postgres" attempted to require "pg-query-stream" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/postgres" attempted to require "pg" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/redshift" attempted to require "pg" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/node-pre-gyp/lib/util" attempted to require "npm" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/node-pre-gyp/lib/util" attempted to require "node-gyp" but could not be resolved, assuming external.
ncc: Module directory "/tmp/629f1c9f/user/node_modules/got" attempted to require "electron" but could not be resolved, assuming external.
```
It seems didn't bundle the node modules. Any thoughts?
